name: Testes Go
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - name: Diagnóstico temporário de módulos
        run: |
          go mod tidy
          echo '--- GO.MOD TIDY ---'
          cat go.mod
          echo '--- GO.SUM TIDY ---'
          cat go.sum
      - run: go test ./...
      - run: go build ./...
